#!/usr/bin/bash
# Run angsd to generate maf file for the AIMs

pure_pop1='batch001_pure_guttulus'
pure_pop2='batch001_pure_geoffroyi'
aims='gut_ld.geo_ld.AIMs.fst0.3000' # file generated by getAIMs.sh

# index aims file
#sort -k1 $aims.txt | sed 's/ /\t/g' > $aims.sorted.txt
sed -ie 's/ /\t/g' $aims.txt
angsd sites index $aims.txt

# allele frequencies for the pure pops
angsd -bam $pure_pop1.txt -GL 2 -doMajorMinor 1 -doMaf 1 -minMapQ 24 -minQ 20 -minInd 5 -minMaf 0.05 -out $pure_pop1.freq -P 5 -sites $aims.txt
angsd -bam $pure_pop2.txt -GL 2 -doMajorMinor 1 -doMaf 1 -minMapQ 24 -minQ 20 -minInd 5 -minMaf 0.05 -out $pure_pop2.freq -P 5 -sites $aims.txt
