#!/usr/bin/bash
# Run angsd to generate maf file for the AIMs

pure_pop1='bamlist_batch001-002_allPure_gut_map1'
pure_pop2='bamlist_batch001-002_allPure_geo_map1'
aims='batch001-002_allPure_gut_map1.batch001-002_allPure_geo_map1.AIMs.fst0.20000' # file generated by getAIMs.sh

# index aims file
#sort -k1 $aims.txt | sed 's/ /\t/g' > $aims.sorted.txt
#sed -ie 's/ /\t/g' $aims.txt
#/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd sites index $aims.txt

# allele frequencies for the pure pops
#/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd -bam $pure_pop1.txt -GL 2 -doMajorMinor 1 -doMaf 1 -minMapQ 24 -minQ 20 -minInd 20 -minMaf 0.05 -out $pure_pop1.freq -P 5 -sites $aims.txt
#/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd -bam $pure_pop2.txt -GL 2 -doMajorMinor 1 -doMaf 1 -minMapQ 24 -minQ 20 -minInd 20 -minMaf 0.05 -out $pure_pop2.freq -P 5 -sites $aims.txt
/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd -bam $pure_pop1.txt -GL 2 -doMajorMinor 1 -doMaf 1 -out $pure_pop1.freq -P 5 -sites $aims.txt
/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd -bam $pure_pop2.txt -GL 2 -doMajorMinor 1 -doMaf 1 -out $pure_pop2.freq -P 5 -sites $aims.txt


