#!/usr/bin/bash
# Run angsd to generate allele frequencies for the AIMs

## input files
pure_pop1='bamlist_batch001-002-oge-1_allPure_gut'
pure_pop2='bamlist_batch001-002-oge-1_allPure_geo'
aims='batch001-002-oge-1_allPure_gut.batch001-002-oge-1_allPure_geo.AIMs.fst0.20000.filtered' # file generated by getAIMs.sh

## index aims file
#sort -k1 $aims.txt | sed 's/ /\t/g' > $aims.sorted.txt
#sed -ie 's/ /\t/g' $aims.txt
/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd sites index $aims.txt

## allele frequencies for the pure pops
/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd -bam $pure_pop1.txt -GL 2 -doMajorMinor 1 -doMaf 1 -out $pure_pop1.freq -P 6 -sites $aims.txt
/apps/conda/fjtrindade/envs/angsd_v0921/bin/angsd -bam $pure_pop2.txt -GL 2 -doMajorMinor 1 -doMaf 1 -out $pure_pop2.freq -P 6 -sites $aims.txt


